// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using troca_de_figurinhas.Models;

namespace trocadefigurinhas.Migrations
{
    [DbContext(typeof(ContextoFigurinhas))]
    partial class ContextoFigurinhasModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("troca_de_figurinhas.Models.Figurinha", b =>
                {
                    b.Property<int>("FigurinhaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<int>("MemberId");

                    b.Property<string>("Nome");

                    b.Property<string>("Numero");

                    b.Property<string>("Quantidade");

                    b.HasKey("FigurinhaId");

                    b.HasIndex("MemberId");

                    b.ToTable("Figurinhas");
                });

            modelBuilder.Entity("troca_de_figurinhas.Models.Member", b =>
                {
                    b.Property<int>("MemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome");

                    b.Property<string>("login");

                    b.Property<string>("senha");

                    b.HasKey("MemberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("troca_de_figurinhas.Models.Figurinha", b =>
                {
                    b.HasOne("troca_de_figurinhas.Models.Member", "Member")
                        .WithMany("Figurinhas")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
